export enum CONTINENT {
  AFRICA = 'AFRICA',
  ANTARCTICA = 'ANTARCTICA',
  ASIA = 'ASIA',
  EUROPE = 'EUROPE',
  NORTH_AMERICA = 'NORTH_AMERICA',
  OCEANIA = 'OCEANIA',
  SOUTH_AMERICA = 'SOUTH_AMERICA'
}
